# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-15 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tb3UIGlobalText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textDesc', models.CharField(db_column='textDesc', default='', max_length=5000, verbose_name='详情')),
                ('textKey', models.CharField(db_column='textKey', max_length=100, unique=True, verbose_name='文本key,中英文数字下划线组合')),
                ('textValue', models.TextField(db_column='textValue', verbose_name='文本value')),
                ('state', models.IntegerField(default=1, verbose_name='状态 0删除 1有效')),
                ('addBy', models.CharField(db_column='addBy', max_length=25, null=True, verbose_name='添加者登录名')),
                ('modBy', models.CharField(db_column='modBy', max_length=25, null=True, verbose_name='修改者登录名')),
                ('addTime', models.DateTimeField(auto_now_add=True, db_column='addTime', verbose_name='创建时间')),
                ('modTime', models.DateTimeField(auto_now=True, db_column='modTime', verbose_name='修改时间')),
            ],
            options={
                'db_table': 'tb3_ui_global_text',
            },
        ),
        migrations.CreateModel(
            name='Tb3UIGlobalVars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varDesc', models.CharField(db_column='varDesc', max_length=5000, verbose_name='详情')),
                ('varKey', models.CharField(db_column='varKey', max_length=100, unique=True, verbose_name='全局变量key,中英文数字下划线组合')),
                ('varValue', models.TextField(db_column='varValue', verbose_name='全局变量value')),
                ('state', models.IntegerField(default=1, verbose_name='状态 0删除 1有效')),
                ('addBy', models.CharField(db_column='addBy', max_length=25, null=True, verbose_name='添加者登录名')),
                ('modBy', models.CharField(db_column='modBy', max_length=25, null=True, verbose_name='修改者登录名')),
                ('addTime', models.DateTimeField(auto_now_add=True, db_column='addTime', verbose_name='创建时间')),
                ('modTime', models.DateTimeField(auto_now=True, db_column='modTime', verbose_name='修改时间')),
            ],
            options={
                'db_table': 'tb3_ui_global_vars',
            },
        ),
        migrations.CreateModel(
            name='Tb3UIPageElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poKey', models.CharField(db_column='poKey', max_length=100, verbose_name='PageObject的key,中英文数字下划线组合')),
                ('elementTitle', models.CharField(db_column='elementTitle', default='', max_length=200, verbose_name='标题')),
                ('elementDesc', models.CharField(db_column='elementDesc', default='', max_length=2000, verbose_name='详情')),
                ('elementKey', models.CharField(db_column='elementKey', default='', max_length=100, verbose_name='elementKey')),
                ('elementType', models.CharField(db_column='elementType', default='', max_length=20, verbose_name='element类型，name id 等等')),
                ('elementValue', models.CharField(db_column='elementValue', default='', max_length=1000, verbose_name='element 值')),
                ('state', models.IntegerField(default=1, verbose_name='状态 0删除 1有效')),
                ('addBy', models.CharField(db_column='addBy', max_length=25, null=True, verbose_name='添加者登录名')),
                ('modBy', models.CharField(db_column='modBy', max_length=25, null=True, verbose_name='修改者登录名')),
                ('addTime', models.DateTimeField(auto_now_add=True, db_column='addTime', verbose_name='创建时间')),
                ('modTime', models.DateTimeField(auto_now=True, db_column='modTime', verbose_name='修改时间')),
            ],
            options={
                'db_table': 'tb3_ui_page_element',
            },
        ),
        migrations.CreateModel(
            name='Tb3UIPageObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poKey', models.CharField(db_column='poKey', max_length=100, unique=True, verbose_name='文本key,中英文数字下划线组合')),
                ('poTitle', models.CharField(db_column='poTitle', default='', max_length=500, verbose_name='详情')),
                ('poDesc', models.CharField(db_column='poDesc', default='', max_length=2000, verbose_name='详情')),
                ('state', models.IntegerField(default=1, verbose_name='状态 0删除 1有效')),
                ('addBy', models.CharField(db_column='addBy', max_length=25, null=True, verbose_name='添加者登录名')),
                ('modBy', models.CharField(db_column='modBy', max_length=25, null=True, verbose_name='修改者登录名')),
                ('addTime', models.DateTimeField(auto_now_add=True, db_column='addTime', verbose_name='创建时间')),
                ('modTime', models.DateTimeField(auto_now=True, db_column='modTime', verbose_name='修改时间')),
            ],
            options={
                'db_table': 'tb3_ui_page_object',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tb3uipageelement',
            unique_together=set([('poKey', 'elementKey')]),
        ),
    ]
