# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-24 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbhttpinterface',
            name='customUri',
            field=models.CharField(db_column='customUri', default='', max_length=200, verbose_name='自定义请求地址'),
        ),
        migrations.AddField(
            model_name='tbhttpinterface',
            name='useCustomUri',
            field=models.IntegerField(db_column='useCustomUri', default=0, verbose_name='是否使用自定义请求地址'),
        ),
        migrations.AddField(
            model_name='tbhttptestcasestep',
            name='customUri',
            field=models.CharField(db_column='customUri', default='', max_length=200, verbose_name='自定义请求地址'),
        ),
        migrations.AddField(
            model_name='tbhttptestcasestep',
            name='stepSwitch',
            field=models.IntegerField(db_column='stepSwitch', default=1, verbose_name='此步骤是否勾选执行'),
        ),
        migrations.AddField(
            model_name='tbhttptestcasestep',
            name='useCustomUri',
            field=models.IntegerField(db_column='useCustomUri', default=0, verbose_name='是否使用自定义请求地址'),
        ),
    ]
