# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-28 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_models', '0004_auto_20190528_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbhttptestcasestep',
            name='uslRedirect',
        ),
        migrations.AddField(
            model_name='tbhttptestcasestep',
            name='urlRedirect',
            field=models.IntegerField(db_column='urlRedirect', default=1, verbose_name='是否自动重定向'),
        ),
    ]
