# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-26 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_models_for_mock', '0002_tb4mockhttp_describe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tb4MockFollower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mockId', models.CharField(db_column='mockId', default='', max_length=50, verbose_name='mock的ID')),
                ('follower', models.CharField(db_column='follower', max_length=25, null=True, verbose_name='关注者邮箱前缀')),
                ('followTime', models.DateTimeField(db_column='followTime', null=True, verbose_name='关注时间')),
                ('state', models.IntegerField(default=1, verbose_name='状态 0删除 1有效')),
                ('addBy', models.CharField(db_column='addBy', max_length=25, null=True, verbose_name='添加者登录名')),
                ('modBy', models.CharField(db_column='modBy', max_length=25, null=True, verbose_name='修改者登录名')),
                ('addTime', models.DateTimeField(auto_now_add=True, db_column='addTime', verbose_name='创建时间')),
                ('modTime', models.DateTimeField(auto_now=True, db_column='modTime', verbose_name='修改时间')),
            ],
            options={
                'db_table': 'tb4_mock_follower',
            },
        ),
    ]
